[ Tiago Braga ] Others - Modal com Query
Mesh-DAO/rentskins_frontend pull request #36
Opened 2023-06-21 15:53 UTC by zTiagok

2023-06-21 17:04 UTC, zTiagok commented
🟨 Checar se há outros modais para abrir com query.

2023-06-22 13:48 UTC, zTiagok commented
@XRow08 pode merger?

2023-06-22 14:29 UTC, XRow08 requested changes
tem q tirar o package-lock.json, esta sendo usado somente o yarn-lock

2023-06-22 18:51 UTC, zTiagok commented
> tem q tirar o package-lock.json, esta sendo usado somente o yarn-lock

Estou com uns problemas no meu yarn, por isso tenho usado o npm, tal o motivo do package-lock. Vou apagar o arquivo, assim que conseguir arrumar vou utilizar apenas o yarn.

2023-06-22 19:04 UTC, XRow08 commented
Apaguei pra vc, valeu

2023-06-22 19:05 UTC, merged

2023-06-22 19:25 UTC, zTiagok commented
> Apaguei pra vc, valeu

Doidera, aqui pra mim não apareceu o package-lock no repo. Vlwzão